include:
  - compose/compose.yaml

services:
  jobmanager:
    build: .
    volumes:
      - ./kafka-dynamic-iceberg-sink/build/libs:/opt/flink/usrlib
      - ./compose/flink/usrconf:/opt/flink/usrconf

  taskmanager:
    image: iceberg-flink-kafka-jobmanager:latest
    volumes:
      - ./kafka-dynamic-iceberg-sink/build/libs:/opt/flink/usrlib
