name=test1
checkpoint.interval=10000

kafka.bootstrap.servers=redpanda:9092
kafka.topics=^postgres\\.public\\..+
kafka.offsets=earliest
kafka.key.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
kafka.value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
kafka.schema.registry.url=http://redpanda:8081

iceberg.catalog.uri=http://rustfs:9000/iceberg
iceberg.catalog.warehouse=warehouse
iceberg.catalog.rest.auth.type=sigv4
iceberg.catalog.rest.signing-region=us-east-1
iceberg.catalog.rest.signing-name=s3
iceberg.catalog.rest.access-key-id=rustfs
iceberg.catalog.s3.endpoint=http://rustfs:9000
iceberg.catalog.client.region=us-east-1
iceberg.catalog.s3.path-style-access=true
iceberg.catalog.s3.access-key-id=rustfs

#iceberg.tables=
iceberg.tables.dynamic-enabled=true
iceberg.tables.route-field=topic
iceberg.tables.route-field-regex=^postgres\\.
#iceberg.tables.route-field-replace=
iceberg.tables.route-field-force-case=lower
#iceberg.tables.default-commit-branch=main
#iceberg.tables.default-id-columns=
#iceberg.tables.default-partition-by=
#iceberg.tables.distribution-mode=
#iceberg.tables.write-parallelism=-1
iceberg.tables.upsert-mode-enabled=true
iceberg.tables.auto-create-enabled=true
iceberg.tables.evolve-schema-enabled=true
iceberg.tables.schema-force-optional=true
iceberg.tables.schema-force-case=lower
#iceberg.tables.schema-case-insensitive=false
iceberg.tables.auto-create-sort-order-by-id-columns=true
iceberg.tables.auto-create-props.write.object-storage.enabled=true
iceberg.tables.auto-create-props.write.object-storage.partitioned-paths=false

#iceberg.table.public.partitioned.route-regex=
#iceberg.table.public.partitioned.commit-branch=main
#iceberg.table.public.partitioned.id-columns=
iceberg.table.public.partitioned.partition-by=day(createdat)
#iceberg.table.public.partitioned.distribution-mode=
#iceberg.table.public.partitioned.write-parallelism=-1
#iceberg.table.public.partitioned.upsert-mode-enabled=false
#iceberg.table.public.partitioned.schema-force-optional=false
#iceberg.table.public.partitioned.schema-force-case=
#iceberg.table.public.partitioned.auto-create-sort-order-by-id-columns=false
#iceberg.table.public.partitioned.auto-create-props.*
