name=test1
kafka.bootstrap.servers=kafka:9092
kafka.topic-pattern=dbserver1.inventory.customers
schema.registry.url=http://schema-registry:8081
iceberg.catalog.uri=http://polaris:8181/api/catalog
iceberg.catalog.warehouse=quickstart_catalog
iceberg.catalog.rest.auth.type=oauth2
iceberg.catalog.oauth2-server-uri=http://polaris:8181/api/catalog/v1/oauth/tokens
iceberg.catalog.scope=PRINCIPAL_ROLE:ALL
iceberg.catalog.header.X-Iceberg-Access-Delegation=vended-credentials
iceberg.table.inventory.customers.partition-by=bucket(id, 2)
# iceberg.catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
# iceberg.catalog.s3.endpoint=http://rustfs:9000
# iceberg.catalog.client.region=us-west-2
# iceberg.catalog.s3.access-key-id=polaris_root
# iceberg.catalog.s3.secret-access-key=polaris_pass
# iceberg.catalog.s3.path-style-access=true