/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.gradleup.shadow") version "9.4.3"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url = uri("https://packages.confluent.io/maven")
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    compileOnly("org.apache.avro:avro:1.12.1")
    compileOnly("org.apache.flink:flink-streaming-java:2.1.3")
    compileOnly("org.apache.flink:flink-table-api-java:2.1.3")
    compileOnly("org.apache.hadoop:hadoop-common:3.4.3")
    compileOnly("org.apache.iceberg:iceberg-core:1.11.0")
    compileOnly("org.apache.iceberg:iceberg-flink-2.1:1.11.0")
    compileOnly("org.slf4j:slf4j-api:2.0.17")

    implementation("io.confluent:kafka-avro-serializer:8.3.0") {
      exclude(group = "org.apache.avro", module = "avro")
    }
    implementation("org.apache.flink:flink-connector-kafka:5.0.0-2.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.github.kinolaev.DataStreamJob"
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
}

tasks.shadowJar {
    relocate("org.apache.avro", "org.apache.iceberg.shaded.org.apache.avro")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
